### POST
POST http://localhost:9000/escalas
Content-Type: application/json

{
    "titulo": "Culto de ceia"
}

### GET
GET http://localhost:9000/escalas

### GET
GET http://localhost:9000/escalas/culto 
Content-Type: application/json

{
    "titulo": "culto de ceia"
}

### GET
GET http://localhost:9000/teste 
Content-Type: application/json

{
    "titulo": "Culto de deia",
    "posicao": 2
}

### PATCH
PATCH  http://localhost:9000/escalas/3e558a44-d791-4c62-920a-17bd538c2aaf
Content-Type: application/json

{
    "culto": "21/12/2024" 
}

### DELETE
DELETE  http://localhost:9000/escalas/3e558a44-d791-4c62-920a-17bd538c2aaf