### POST
POST http://localhost:9000/usuarios
Content-Type: application/json

{
    "nome": "Bruno",
    "sobrenome": "Santos",
    "email": "brunosemail.com",
    "senha": "Brunosds1@",
    "cargo": "Musico",
    "naipe": "Teclado"
}

### GET
GET http://localhost:9000/usuarios

### GET
GET http://localhost:9000/usuarios/1

### GET
GET http://localhost:9000/usuarios/bruno

### PATCH
PATCH http://localhost:9000/usuarios/1
Content-Type: application/json
{
    
}

### DELETE
DELETE http://localhost:9000/usuarios/1
