### POST
POST http://localhost:9000/usuarios
Content-Type: application/json

{
    "nome": "Alex",
    "sobrenome": "Silva",
    "email": "silvalex@email.com",
    "senha": "7890",
    "cargo": "Musico",
    "naipe": "Guitarra"
}

### GET
GET http://localhost:9000/usuarios

### GET 
GET http://localhost:9000/usuarios/usuario_id?id=b7f085c3-b7ee-4a13-9597-4e36c808b45f


### POST
POST http://localhost:9000/usuarios/nome 
Content-Type: application/json

{
    "nome": "Camila"
}

### PATCH 
PATCH  http://localhost:9000/usuarios/editar/447c4ece-89bc-40a0-8e42-d2a42a386011
Content-Type: application/json

{
    "nome": "",
    "sobrenome": "",
    "cargo": "Ministro",
    "naipe": "Contralto"
}

### DELETE
DELETE http://localhost:9000/usuarios/apagar?id=7483843f-49c2-49b9-8f9a-f295836ab8f7
