### POST
POST http://localhost:9000/usuarios
Content-Type: application/json

{
    "nome": "Paulo",
    "sobrenome": "Nascimento",
    "email": "pnascimento@email.com",
    "senha": "1234",
    "cargo": "Musico",
    "naipe": "Baixo"
}

### GET
GET http://localhost:9000/usuarios

### GET 
GET http://localhost:9000/usuarios/usuario_id?id=2604a86b-84f7-4010-b843-f1abeb6d60ca


### POST
POST http://localhost:9000/usuarios/nome 
Content-Type: application/json

{
    "nome": "Camila"
}

### PATCH 
PATCH  http://localhost:9000/usuarios/editar/368cfb71-67f5-4348-8831-11a62979d620
Content-Type: application/json

{
    "nome": "",
    "sobrenome": "Alves",
    "cargo": "Vocal",
    "naipe": "Soprano"
}

### DELETE
DELETE http://localhost:9000/usuarios/apagar?id=7483843f-49c2-49b9-8f9a-f295836ab8f7
